<?php
// $Id$


//----------------------------------------------------------------------------
// Core hooks.

/**
 * Implementation of hook_requirements().
 */
function hs_views_taxonomy_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {
    $pattern = <<<EOT
function _views_build_filters_form(\$view) {
  // When the form is retrieved through an AJAX callback, the cache hasn't
  // been loaded yet. The cache is necesssary for _views_get_filters().
  views_load_cache();
EOT;
    $views_with_patch_257004 = preg_match('#'. preg_quote($pattern) .'#m', file_get_contents(drupal_get_path('module', 'views') .'/views.module'));

    if ($views_with_patch_257004) {
      $value = t('The Views module is new enough.');
      $description = '';
      $severity = REQUIREMENT_OK;
    }
    else {
      $value = t('The Views module is outdated.');
      $description = t("The version of Views that you have installed is either
        older than May 11, 2008, or doesn't have the obligatory patch applied.
        Please apply the <a href=\"!patch_url\">patch</a> or update to a newer
        version of the Views module!",
        array('!patch_url' => 'http://drupal.org/files/issues/hs_compatibility.patch')
      );
      $severity = REQUIREMENT_ERROR;      
    }

    $requirements['hs_views_taxonomy'] = array(
      'title'       => t('Hierarchical Select Views Taxonomy'),
      'value'       => $value,
      'description' => $description,
      'severity'    => $severity,
    );
  }

  return $requirements;
}


//----------------------------------------------------------------------------
// Hierarchical Select hooks.

/**
 * Implementation of hook_hierarchical_select_form_alter().
 */
function hs_views_taxonomy_hierarchical_select_form_alter($form_id, &$form) {
  // Change the exposed filters of Views. Only affects hierarchical vocabulary
  // filters.
  if (in_array($form_id, array('views_filters', 'views_filterblock'))) {
    $hs_exposed_filters_found = 0;

    // Find the ids and vocabulary ids of the exposed filters.
    foreach ($form['view']['#value']->exposed_filter as $id => $filter) {
      if (preg_match("/term_node_(\d+)\.tid/", $filter['field'], $matches)) {
        $vid = $matches[1];
        
        // Only apply Hierarchical Select if it's enabled for this vocabulary.
        if (variable_get("taxonomy_hierarchical_select_$vid", 0)) {
          $hs_exposed_filters_found++;
          $vocabulary = taxonomy_get_vocabulary($vid);
          $view = $form['view']['#value'];

          // Hierarchical Select only makes sense if there's a hierarchy.
          if ($vocabulary->hierarchy > 0) {
            // Make it use a hierarchical select.
            $form["filter$id"]['#type'] = 'hierarchical_select';
            $form["filter$id"]['#config'] = array(
              'module' => 'hs_views_taxonomy',
              'params' => array(
                'vid' => $vid,
              ),
              // When the **ALL** option is selected, nothing else should be.
              'exclusive_lineages' => array('**ALL**'),
              // This is a GET form, so also render the flat select.
              'render_flat_select' => 1,
            );
            taxonomy_hierarchical_select_update_form_item($form["filter$id"], $vid);
            
            // Inherit #config['dropbox']['status'] from the exposed filter
            // settings.
            $form["filter$id"]['#config']['dropbox']['status'] = !((bool) $view->exposed_filter[$id]['single']);
            
            // Inherit #required from the exposed filter settings.
            $form["filter$id"]['#required'] = !((bool) $view->exposed_filter[$id]['optional']);
          
            // Remove the dropbox limit.
            unset($form["filter$id"]['#config']['dropbox']['limit']);

            // Put the altered exposed filters in a separate table row.
            require_once(drupal_get_path('module', 'hierarchical_select') .'/includes/common.inc');
            hierarchical_select_common_views_exposed_filters_reposition();
          }
        }
      }
    }

    if ($hs_exposed_filters_found > 0) {
      // Views will remove the form_id in views_filters_process(), but we need
      // it for Hierarchical Select to work, so put it back.
      $form['copy_of_form_id'] = $form['form_id'] + array('#parents' => array('form_id'));
    }
  }
}

/**
 * Implementation of hook_hierarchical_select_params().
 */
function hs_views_taxonomy_hierarchical_select_params() {
  return taxonomy_hierarchical_select_params();
}

/**
 * Implementation of hook_hierarchical_select_root_level().
 */
function hs_views_taxonomy_hierarchical_select_root_level($params) {
  return array('**ALL**' => '<'. t('all') .'>') + taxonomy_hierarchical_select_root_level($params);
}

/**
 * Implementation of hook_hierarchical_select_children().
 */
function hs_views_taxonomy_hierarchical_select_children($parent, $params) {
  return ($parent == '**ALL**') ? array() : taxonomy_hierarchical_select_children($parent, $params);
}

/**
 * Implementation of hook_hierarchical_select_lineage().
 */
function hs_views_taxonomy_hierarchical_select_lineage($item, $params) {
  return ($item == '**ALL**') ? array($item) : taxonomy_hierarchical_select_lineage($item, $params);
}

/**
 * Implementation of hook_hierarchical_select_valid_item().
 */
function hs_views_taxonomy_hierarchical_select_valid_item($item, $params) {
  return ($item == '**ALL**' || taxonomy_hierarchical_select_valid_item($item, $params));
}

/**
 * Implementation of hook_hierarchical_select_item_get_label().
 */
function hs_views_taxonomy_hierarchical_select_item_get_label($item, $params) {
  return ($item == '**ALL**') ? '<'. t('all') .'>' : taxonomy_hierarchical_select_item_get_label($item, $params);
}


/**
 * Implementation of hook_hierarchical_select_create_item().
 */
// No implementation. This doesn't make sense for exposed filters: if you were
// able to create new items in the hierarchy, how could you then possibly find
// anything for that item?

/**
 * Implementation of hook_hierarchical_select_node_count().
 */
function hs_views_taxonomy_hierarchical_select_node_count($item, $params) {
  if ($item == '**ALL**') {
    return db_result(db_query('SELECT COUNT(DISTINCT(nid)) FROM {term_node}'));
  }
  else {
    return taxonomy_hierarchical_select_node_count($item, $params);
  }
}
